# Generated by Django 4.2.1 on 2024-01-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.CharField(max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=20, null=True)),
                ('category', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
