# Generated by Django 3.2.12 on 2024-01-19 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=10, null=True)),
                ('decription', models.CharField(max_length=100, null=True)),
                ('date', models.CharField(default=datetime.datetime.now, max_length=20)),
            ],
        ),
    ]
