# Generated by Django 4.2.1 on 2024-01-19 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.CharField(default=datetime.datetime.today, max_length=20),
        ),
    ]
